import mongoose from "mongoose"

const examinationSchema = new mongoose.Schema({
    title:{
        type:String
    },
    description:{
        type:String
    },
    grade:{
        type: [Number]
    },
    time:{
        type:Number
    },
    programs:{
        type:[String]
    },
    
    numberOfQuestions:{
        type:Number
    },
    attemptsAllowed:{
        type:Number
    },
    publish:{
        type:Boolean
    },
    image:{
        type:String
    },
    allowQuizReview:{
        type:Boolean
    },
    questions:{
        type:[Object]
    },
    featured:{
        type:Boolean
    },
    displayScores:{
        type:Boolean
    },
    showFeedBackForm:{
        type:Boolean
    },
    contest:{
        type:Boolean
    },
    registered:{
        type:[String],
        default:[""]
    },
    cost:{
        type:String
    },
    type:{
        type:String
    },
    features:{
        type:[String]
    },
    tags:{
        type:[String]
    },
    level:{
        type:String
    },
    instructor:{
        type:String
    },
    shuffleQuestions:{
        type:Boolean
    },
    contest:{
        type:Boolean
    },
    bonusTimeLimit:{
        type:String
    },
    pointsPerQuestion:{
        type:String
    },
    estimatedTime:{
        type:String
    },
    contestType:{
        type:String
    },
    difficulty:{
        type:String
    },
    endTime:{
        type:String
    },
    examMode:{
        type:Boolean,
        
    },
    instructions:{
        type:String
    }
}, {timestamps:true})

export const examinationModel = mongoose.model("exam",examinationSchema)